spring:
  application:
    name: Rating-Service

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/rating_service
    name: rating_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
